exchange_mapper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'Exchange Mapper Administration'
admin.site.site_title = 'Exchange Mapper Admin Portal'
admin.site.index_title = 'Welcome to Exchange Mapper Admin Portal'

handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'
handler403 = 'main.views.error_403'
handler400 = 'main.views.error_400'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('', include(('sso.urls', 'sso'), namespace='sso')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include

from . import views
from .views import *
from django.views.generic import TemplateView
# decorators
from django.contrib.auth.decorators import login_required

app_name = 'main'
urlpatterns = [
    # BASIC

    # login button
    path('', views.render_login_button, name='login_button'),
    path('captcha/', include('captcha.urls')),
    path('mapper/', views.home, name='mapper_home'),
    path('guide/', login_required(TemplateView.as_view(template_name="main/guide_new.html")), name='guide'),
    # home url
    #path('home', views.home, name='home'),
    #path('search/', views.SearchResultsView.as_view(),name="search_results"),
    # path('form/',views.userinput,name="userinput"),
    # path('blog/',views.BlogListView.as_view(),name='blog'),
    path('blogs/', views.blog, name='blog'),
    #path('search/', views.SearchResultsView.as_view(),name="searchresults"),
    # path('home/',views.userinput,name='home'),
    #path('university', views.university, name = 'university'),
    #path('blog/<int:pk>/detail/', BlogDetailView.as_view(), name='experience-detail'),
    path('blog/<int:pk>/', views.blog_detail_view, name='experience-detail'),
    path('add_your_CM', views.yourExperience, name='your_exp'),
    path('write_blog/', views.experienceform, name='fill_exp'),
    # path('add_uni/',views.addUniversity, name = 'add_uni'),
    path('forum/', views.query_view, name='doubt'),
    path('query_form/', views.doubt_form_view, name='doubt-form'),
    path('f_answer/<int:pk>', views.answer_view, name='answer'),
    path('f_answerform/<int:id>', views.answer_view_form, name='answer-form'),
    path('upvote/<int:pk>/<int:id>', views.upvote_view, name='upvote'),
    path('downvote/<int:pk>/<int:id>', views.downvote_view, name='downvote'),
    path('team/', views.team_view, name='team'),
]

sso/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path("login/", views.redirect_to_login, name="login"),
    path("complete/", views.authenticate_code, name="auth_complete"),
    path("logout/", views.client_logout, name="logout"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# For current date and time
from django.utils import timezone
# Create your models here.
from django.dispatch import receiver
import os

User.has_usable_password = False
seasons = [
    ('S', 'Spring'),
    ('A', 'Autumn'),
]
years = [
    ('2', 'Second year'),
    ('3', 'Third year'),
    ('4', 'Fourth year'),
    ('5', 'Dual Degree'),
]


class UserInfo(models.Model):
    # link to Django User Model
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='userinfo', blank=True, null=True)

    # additional data from SSO
    name = models.CharField(max_length=200)
    roll_number = models.CharField(max_length=20)
    department = models.CharField(max_length=200, null=True, blank=True)
    join_year = models.IntegerField(null=True, blank=True)
    graduation_year = models.IntegerField(null=True, blank=True)
    degree = models.CharField(max_length=300, null=True, blank=True)
    email_ldap = models.CharField(max_length=200)
    upvoted = models.ManyToManyField('Answer', related_name='upuser')
    downvoted = models.ManyToManyField('Answer', related_name='downuser')

    def __str__(self):
        return self.name


class University(models.Model):
    id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=500)
    country = models.CharField(max_length=60, default=0, blank=False)

    class Meta:
        ordering = ('fullname',)

    def __str__(self):
        return self.fullname


class Department(models.Model):
    code = models.CharField(max_length=6)
    fullname = models.CharField(max_length=500)
    #university = models.ManyToManyField(University)
    # University = models.ManyToManyField(University)

    class Meta:
        ordering = ('fullname',)

    def __str__(self):
        return (self.fullname)


class HomeCourse(models.Model):
    code = models.CharField(max_length=200)
    name = models.CharField(max_length=400, null=True)
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.code


class RemoteCourse(models.Model):
    UserInfo = models.ForeignKey(
        UserInfo, on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(max_length=200)
    name = models.CharField(max_length=400, null=True)
    homecourse = models.ForeignKey(
        HomeCourse, on_delete=models.CASCADE, null=False, blank=False)
    university = models.ForeignKey(
        University, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return(self.name+" - "+" - "+self.university.fullname)


class CourseMap(models.Model):
    UserInfo = models.ForeignKey(
        UserInfo, on_delete=models.CASCADE, null=True, blank=True)
    University = models.ForeignKey(
        University, on_delete=models.CASCADE, null=True, blank=True)
    season = models.CharField(
        max_length=1,
        choices=seasons,
        default='S',
    )
    year = models.CharField(
        max_length=1,
        choices=years,
        default='2'
    )
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    remote_courses = models.ManyToManyField(RemoteCourse)

    #department = models.CharField(max_length=400,null=True)
    def __str__(self):
        return (self.UserInfo.name+"'s CourseMap")


class Expierence(models.Model):
    # UserInfo = models.ForeignKey(UserInfo,on_delete=models.CASCADE, null=True, blank=True)
    UserInfo = models.OneToOneField(
        UserInfo, on_delete=models.CASCADE, null=True, blank=True)
    # Blog_text = models.CharField(max_length=400,null=True)
    para1 = models.CharField(max_length=2500, null=True)
    para2 = models.CharField(max_length=2500, null=True)
    para3 = models.CharField(max_length=2500, null=True)
    img1 = models.ImageField(upload_to='images/')
    img2 = models.ImageField(upload_to='images/')
    img3 = models.ImageField(upload_to='images/')
    iframe = models.CharField(max_length=400, blank=True, null=True)
    is_verified = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return (self.UserInfo.name+"'s Experience")


@receiver(models.signals.post_delete, sender=Expierence)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.img1:
        if os.path.isfile(instance.img1.path):
            os.remove(instance.img1.path)
    if instance.img2:
        if os.path.isfile(instance.img2.path):
            os.remove(instance.img2.path)
    if instance.img3:
        if os.path.isfile(instance.img3.path):
            os.remove(instance.img3.path)


@receiver(models.signals.pre_save, sender=Expierence)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file1 = sender.objects.get(pk=instance.pk).img1
        old_file2 = sender.objects.get(pk=instance.pk).img2
        old_file3 = sender.objects.get(pk=instance.pk).img3
    except sender.DoesNotExist:
        return False

    new_file1 = instance.img1
    new_file2 = instance.img2
    new_file3 = instance.img3
    if not old_file1 == new_file1:
        if os.path.isfile(old_file1.path):
            os.remove(old_file1.path)
    if not old_file2 == new_file2:
        if os.path.isfile(old_file2.path):
            os.remove(old_file2.path)
    if not old_file3 == new_file3:
        if os.path.isfile(old_file3.path):
            os.remove(old_file3.path)


class Comment(models.Model):
    experience = models.ForeignKey(Expierence, on_delete=models.CASCADE)
    # writer = models.ForeignKey(User, on_delete=models.CASCADE)
    writer = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    date_posted = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return (self.writer.name+" commented on " + self.experience.UserInfo.name + "'s Experience")


class Doubt(models.Model):
    student = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    date_posted = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return (self.text[0:50])


class Answer(models.Model):
    author = models.ForeignKey(
        UserInfo, on_delete=models.CASCADE, null=True, blank=True)
    text = models.CharField(max_length=2500)
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)
    doubt = models.ForeignKey(Doubt, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return (self.doubt.text[0:20] + ' -> ' + self.text[0:20])


#------PENDING--------------#
"""

Delete button functionality
add university search filter in blog

"""


#-----FIXED------------#
"""
Change depratment to list
Add max height condition in blog details
add up icon in voting
Add iirc logo in the login page (UGAC | iirc)
blog detail view first para details of exchange
remove extra scroll bar in landing page
Ask for bg image for landing page
<script src="three.r119.min.js"></script>
<script src="vanta.birds.min.js"></script>
<script>
VANTA.BIRDS({
  el: "#your-element-selector",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 200.00,
  minWidth: 200.00,
  scale: 1.00,
  scaleMobile: 1.00,
  birdSize: 1.50,
  wingSpan: 31.00,
  quantity: 4.00
})
</script>
fix images size in blog
decrease width of doubt/answer accordion box and answer form,new question form
blog post change warning UI
click on image to read more
Blog finalize design 
change mapper dropdown, ask for button
in mapper increase margin-bottom between buttons (ask design team)
try increasing the width of modal
change guide, add popup and close button for additional info (w3Schools for popup)
add a paragraph in guide for intro info (PHd dont include)
Ask for footer
Fix the landing page url
FIx the include nav in landing page
Add coursemap button in mapper itself
Add 'all' when none is selected
Add grid in mapper
"""
# redirect of your_exp
# Department should be textfield in INPUT
# Should display all maps by default
# input taken in course map
# Remote course mei add user field
# Added home dept display in user interface
# Change the input of -----
# Add is verified filter
# Minor Course can be of diff dept --> Maps are being filtered using Home Department only
#Univer - RemoteCourse
# dept - HomeCourses filter added
# Semester should be of our clg ony -->The related homecourses are being queried for filtering , fixed

main/forms.py
from dal import autocomplete
from django import forms
from django.forms import modelformset_factory
from main.models import *
from captcha.fields import CaptchaField
from ckeditor.widgets import CKEditorWidget

seasons = [
    ('None', 'All'),
    ('S', 'Spring'),
    ('A', 'Autumn'),
]

seasons2 = [
    ('S', 'Spring'),
    ('A', 'Autumn'),
]
years = [
    ('None', 'All'),
    ('2', 'Second year'),
    ('3', 'Third year'),
    ('4', 'Fourth year'),
    ('5', 'Dual Degree'),
]

years2 = [
    ('2', 'Second year'),
    ('3', 'Third year'),
    ('4', 'Fourth year'),
    ('5', 'Dual Degree'),
]

Uni = University.objects.all()
Uni_list = [('None', 'All')]
for u in Uni:
    name = u.fullname
    id_of_uni = u.id
    Uni_list.append((id_of_uni, name))

Dept = Department.objects.all()
Dept_list = [('None', 'All')]
for d in Dept:
    code = d.code
    name = d.fullname
    Dept_list.append((code, name))


class CaptchaLoginForm(forms.Form):
    captcha = CaptchaField(label="Enter the captcha")


class InputForm(forms.Form):
    # University = forms.ModelChoiceField(required=False, queryset=University.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}),empty_label="All")
    University = forms.ChoiceField(choices=Uni_list)
    semester = forms.ChoiceField(choices=seasons)
    year = forms.ChoiceField(choices=years)
    department = forms.ChoiceField(choices=Dept_list)

"""
class UniversityInputForm(forms.Form):
    fullname = forms.CharField(label='University Name', max_length=100)
    University = forms.ChoiceField(choices=Universities)
"""

class CommentForm(forms.Form):
    comment = forms.CharField(max_length=1000, label="Leave a comment",
                              widget=forms.Textarea(attrs={'autocomplete': 'off','rows':2, 'cols':15}))


class ExperienceForm(forms.Form):
    #para1 = forms.CharField(max_length = 400,widget=CKEditorWidget())
    para1 = forms.CharField(
        max_length=2500, widget=forms.Textarea(attrs={'rows':3, 'cols':15}), label="Introduction")
    para2 = forms.CharField(max_length=2500, widget=forms.Textarea(attrs={'rows':3, 'cols':15}),label="Experience")
    para3 = forms.CharField(max_length=2500, widget=forms.Textarea(attrs={'rows':3, 'cols':15}),label="Conclusion")
    img1 = forms.ImageField(label="Profile picture")
    img2 = forms.ImageField(label="Blog Picture 1")
    img3 = forms.ImageField(label="Blog Picture 2")
    iframe = forms.URLField(required=False)


""""
class UniversityForm(forms.Form):
	fullname = forms.CharField(max_length = 500)
	city = forms.CharField(max_length = 60)
	country = forms.CharField(max_length = 60)
"""
class seasonAndYearForm(forms.Form):
    # University = forms.ModelChoiceField(required=False, queryset=University.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}),empty_label="All")
    season = forms.ChoiceField(choices=seasons2)
    year = forms.ChoiceField(choices=years2)

class UniversityOnlyForm(forms.Form):
    University = forms.ModelChoiceField(
        required=True,queryset=University.objects.all())
"""
class seasonOnlyForm(forms.Form):
    University = forms.ModelChoiceField(
        required=True,queryset=University.objects.all())
"""

RemotecourseModelFormset = modelformset_factory(
    RemoteCourse,
    # initial = [{'UserInfo' : }],
    fields=('UserInfo', 'code', 'name','homecourse',),
    # widgets = {'homecourse': autocomplete.ModelSelect2(url='main:your_exp')},
    extra=1,
)


class DoubtForm(forms.Form):
    text = forms.CharField(max_length=1000, label="Query",
                           widget=forms.Textarea(attrs={'rows':2, 'cols':15,'autocomplete': 'off'}))


privacy = [(True, 'Anonymous')]


class AnswerForm(forms.Form):
    text = forms.CharField(max_length=2500, widget=forms.Textarea(
        attrs={'autocomplete': 'off','rows':4, 'cols':15,}))
    anonymous = forms.ChoiceField(choices=privacy, widget=forms.RadioSelect,
                                  required=False, label="Check the button to answer anonymously")


class SearchForm(forms.Form):
    university_search = forms.CharField(
        max_length=500, required=False, label="Search Blogs By University...")


"""
RemotecourseModelFormset = modelformset_factory(
	RemoteCourse,
	fields=('code','name','department','homecourse','season','year','university'),
	extra=1,
	# widgets={
	# 	'name': forms.TextInput(attrs={
	# 		'class':'',
	# 		'placeholder':''
	# 	})
	# }
)
"""

main/templates/main/landing_page.html
{%extends 'main/base.html'%}{%load static%} {%block content%}
<link rel="stylesheet" href=" {% static 'main/landing_page.css' %}  ">
<div class="jumbotron-fluid">
    <div class="container-fluid">
        <div class="text-center">
            <div class="display-4" style="color: black;">Welcome {{current_name}} </div>
            <div id="mapperbutton"><a class="btn btn-primary" href="{% url 'main:mapper_home' %}">
                Go to Mapper
            </a></div>
        </div>
        <!--div class="row h-100 justify-content-center align-items-center">
            <div class="col-10">

            </div>
        </div-->
    </div>
</div>
<!---Optional JavaScript-->
<!--jQuery first, then Popper.js, then Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {%endblock%}

main/templates/main/landing_page_new.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exchange Mapper</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/nav.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.3/particles.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');
        * {
            margin: 0;
            padding: 0;
            font-family: 'Roboto', sans-serif;
            font-weight: 600 !important;
        }
        
        .main_text {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 88.5vh;
            position: relative;
            background-color: #1e1f26;
            text-align: center;
            padding: 0 2em;
        }
        
        .main_text h1 {
            font-size: 5vw;
            margin: 0;
            padding-bottom: 0.5rem;
            letter-spacing: 0.3rem;
            color: #03dac6;
            transition: all 0.3s ease;
            z-index: 3;
        }
        
        h1:hover {
            transform: translate3d(0, -10px, 22px);
            color: #ff0266;
        }
        
        .main_text h2 {
            font-size: 2vw;
            letter-spacing: 0.3rem;
            font-family: "ROBOTO", sans-serif;
            font-weight: 300;
            color: #faebd7;
            z-index: 4;
        }
        
        .background {
            position: absolute;
            height: 100vh !important;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 0;
        }
        
        @media (min-width: 800px) {
            .main_text h1,
            .nav {
                font-size: 5vw;
            }
            .main_text h2,
            .slider h2 {
                font-size: 3vw;
            }
            .main_text-tab {
                font-size: 3vw;
            }
        }
        
        @media screen only (min-width: 360px) {
            .main_text h1,
            .nav {
                font-size: 8vw;
            }
            .main_text h2,
            .slider h2 {
                font-size: 2vw;
                letter-spacing: 0.2vw;
            }
        }
        
        .background {
            /* position: absolute;*/
            height: 100vh;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 0;
        }
        
        .buttons {
            overflow: hidden;
        }
        
        .buttons>div {
            width: calc(50% - 40px);
            padding: 20px;
            float: left;
            position: fixed;
            bottom: 0;
            top: 0;
        }
        
        .buttons .dark {
            background: #000;
            left: 50%;
        }
        
        .buttons a {
            float: left;
            margin-right: 20px;
            margin-bottom: 20px;
        }
        
        a#link {
            position: absolute;
            left: 20px;
            bottom: 10px;
            text-decoration: none;
            color: #555;
            font-weight: bold;
        }
        /*------------------------------------------------------*/
        /* BUTTONS */
        /*------------------------------------------------------*/
        
        .btn,
        input[type="submit"] {
            cursor: pointer;
            border-radius: 0px;
            text-decoration: none;
            padding: 12px 18px;
            font-size: 12px;
            line-height: 19px;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 400;
            letter-spacing: 3px;
            -webkit-transition: all .4s ease-in-out;
            -moz-transition: all .4s ease-in-out;
            -ms-transition: all .4s ease-in-out;
            -o-transition: all .4s ease-in-out;
            transition: all .4s ease-in-out;
        }
        
        .btn-mid {
            border-radius: 0px;
            text-decoration: none;
            padding: 14px 21px;
            font-size: 13px;
            line-height: 25px;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 400;
            letter-spacing: 3px;
            -webkit-transition: all .4s ease-in-out;
            -moz-transition: all .4s ease-in-out;
            -ms-transition: all .4s ease-in-out;
            -o-transition: all .4s ease-in-out;
            transition: all .4s ease-in-out;
        }
        
        .btn:hover,
        input[type="submit"]:hover {
            -webkit-transition: all .4s ease-in-out;
            -moz-transition: all .4s ease-in-out;
            -ms-transition: all .4s ease-in-out;
            -o-transition: all .4s ease-in-out;
            transition: all .4s ease-in-out;
        }
        
        .btn-white {
            border: solid 2px #fff;
            background: transparent;
            color: #fff !important;
        }
        
        .btn-white:hover {
            border: solid 2px #fff;
            background: #fff;
            color: #1f1f1f !important;
        }
        
        .btn-dark,
        input[type="submit"] {
            border: solid 2px #1f1f1f;
            background: transparent;
            color: #1f1f1f;
        }
        
        .btn-dark:hover,
        input[type="submit"]:hover,
        .btn-dark.active {
            border: solid 2px #1f1f1f;
            background: #1f1f1f;
            color: #fff;
        }
        
        .btn-color {
            background: transparent;
        }
        
        .btn-color:hover {
            color: #fff;
        }
        
        @media screen and (max-width: 800px) {
            .btn {
                font-size: 8px !important;
                padding: 5px 7px;
            }
            .navbar-collapse {
                z-index: 2 !important;
            }
        }
        
        .navbar-dark .navbar-toggler-icon {
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'%3e%3cpath stroke='rgba(255,255,255, 0.5)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
        }
        
        .navbar-dark .navbar-toggler {
            background-color: #21D6E7 !important;
        }
        
        @media screen and (max-width: 600px) {
            .navbar-custom h2,
            h4 {
                font-size: 1rem !important;
            }
        }
        
        @media screen and (max-width: 350px) {
            .navbar-custom h2,
            h4 {
                font-size: 1rem !important;
            }
        }
    </style>
    <script type="text/javascript">
        window.onload = function() {
            Particles.init({
                selector: ".background"
            });
        };
        var particles = Particles.init({
            selector: ".background",
            color: ["#03dac6", "#ff0266", "#000000"],
            connectParticles: true,
            responsive: [{
                breakpoint: 768,
                options: {
                    color: ["#faebd7", "#03dac6", "#ff0266"],
                    maxParticles: 33,
                    connectParticles: false
                }
            }]
        });
    </script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-light py-2 navbar-custom" style="margin-bottom:0px;background-color: #222222 !important;z-index: 1;">
        <a class="navbar-brand" href="{%url 'main:login_button'%}">
            <h2>Exchange Mapper</h2>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">

                {% if user.is_staff %}
                <li class="nav-item ">
                    <h4><a class="nav-link " href="{%url 'admin:index' %} ">Admin</a></h4>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:guide' %}">
                        <h4>Guide</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'main:mapper_home'%}">
                        <h4>Mapper</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:blog' %}">
                        <h4>Blogs</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:doubt' %}">
                        <h4>Forum</h4>
                    </a>
                </li>
                <li class="nav-item ">
                    <h4><a class="nav-link " href="{%url 'sso:logout' %} ">Logout</a></h4>
                </li>
            </ul>
        </div>
    </nav>
    <section class="main_text">
        <h1>Welcome to Exchange Mapper,</h1>
        <h2> {{current_name}} </h2>
        <a class="btn btn-white btn-mid" href="{%url 'main:mapper_home'%}" style="z-index: 1;font-family:'Roboto', sans-serif;">GO TO MAPPER</a>
    </section>
    <canvas class="background"></canvas>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>